#!/bin/bash
# chkconfig: 2345 85 15
# description: order_system High Performance Socket Service

### BEGIN INIT INFO
# Provides:          order_system
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: order_system High Performance Socket Service
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME=__SERVICE_NAME__
USER=__USER__
GROUP=__GROUP__
DAEMON=__PHP_ARTISAN_PWD__/tool

# Read configuration variable file if it is present
[ -r /etc/default/${NAME} ] && . /etc/default/${NAME}

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

start() {
    start-stop-daemon --start --chuid ${USER}:${GROUP} --exec ${DAEMON} -- Service start
}

stop() {
    ${DAEMON} Service stop
}

reload() {
    start-stop-daemon --start --chuid ${USER}:${GROUP} --exec ${DAEMON} -- Service reload
}

restart() {
    start-stop-daemon --start --chuid ${USER}:${GROUP} --exec ${DAEMON} -- Service restart
}

status() {
    ${DAEMON} Service status
    exit $?
}

case "$1" in
    start|stop|reload|restart|status)
        $1
        ;;
    *)
          echo $"Usage: $0 {start|stop|status|reload|restart}"
          exit 2
          ;;
esac
